kind: ConfigMap
apiVersion: v1
metadata:
  name: gcs-proxy-config
  labels:
    app: gcs-proxy
    component: nginx
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  # NGINX config influenced by https://github.com/presslabs/gs-proxy
  proxy.conf: |
      upstream gs {
            server                   storage.googleapis.com:443;
            keepalive                128;
      }

      {{- range $bucket := .Values.gcsProxy.buckets }}
      server {
            listen 80;
            server_name {{ $bucket.host }};
            if ( $request_method !~ "GET|HEAD" ) {
                  return 405;
            }

            location / {
                  rewrite /$ /index.html;

                  proxy_set_header        Host storage.googleapis.com;
                  proxy_pass              https://gs/{{ $bucket.name }}$uri;
                  proxy_http_version      1.1;
                  proxy_set_header        Connection "";

                  gzip                    on;
                  gzip_proxied            any;

                  proxy_intercept_errors on;
                  proxy_hide_header       alt-svc;
                  proxy_hide_header       X-GUploader-UploadID;
                  proxy_hide_header       alternate-protocol;
                  proxy_hide_header       x-goog-hash;
                  proxy_hide_header       x-goog-generation;
                  proxy_hide_header       x-goog-metageneration;
                  proxy_hide_header       x-goog-stored-content-encoding;
                  proxy_hide_header       x-goog-stored-content-length;
                  proxy_hide_header       x-goog-storage-class;
                  proxy_hide_header       x-xss-protection;
                  proxy_hide_header       accept-ranges;
                  proxy_hide_header       Set-Cookie;
                  proxy_ignore_headers    Set-Cookie;
            }
      }
      {{ end }}
